doctrine/mongodb

lib/Doctrine/MongoDB/Collection.php
lib/Doctrine/MongoDB/CommandCursor.php
lib/Doctrine/MongoDB/Database.php
lib/Doctrine/MongoDB/Event/AggregateEventArgs.php
lib/Doctrine/MongoDB/LoggableCollection.php
lib/Doctrine/MongoDB/LoggableDatabase.php
tests/Doctrine/MongoDB/Tests/BaseTest.php
tests/Doctrine/MongoDB/Tests/CollectionTest.php
tests/Doctrine/MongoDB/Tests/CommandCursorFunctionalTest.php
tests/Doctrine/MongoDB/Tests/CommandCursorTest.php
tests/Doctrine/MongoDB/Tests/DatabaseTest.php

Supersedes #187. Fixes #189.
With driver 1.5.x, we cannot support both cursor resetting *and* socket timeouts. Cursor resetting (via `rewind()`) is necessary for the command cursor wrapper to properly implement Countable, which Doctrine's Iterator extends. Using the `createFromDocument()` factory method means we can't rewind/reset the cursor. Ultimately, this PR uses `MongoCollection::aggregateCursor()` and favors the ability to rewind the cursor over supporting a socket timeout on 1.5.x.
Related tasks:

Support aggregation command cursors and client options

---

lib/Doctrine/MongoDB/Query/Query.php

Don't pass empty arrays to array_combine()

---

lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php
tests/Doctrine/MongoDB/Tests/Query/ExprTest.php

This PR adds support for the ```$bit```, ```$currentDate```, ```$max```, ```$min```, ```$mul``` and ```$position``` update operators added in MongoDB 2.6.
Fixes #136.

Query builder support for new update operators in MongoDB 2.6

---

lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php

This changes the $currentDate operator to no longer accept a timestamp parameter, instead accepting the type directly.
Fixes #217

Change parameter for $currentDate operator

---

lib/Doctrine/MongoDB/Cursor.php
lib/Doctrine/MongoDB/CursorInterface.php
lib/Doctrine/MongoDB/EagerCursor.php

This PR aims to fix #208 by adding a common ```CursorInterface``` which contains most methods from ```MongoCursor``` and aims to have ```Cursor``` and ```EagerCursor``` provide the same functionality. Note that ```EagerCursor``` will delegate all calls to the wrapped ```Cursor``` instance. It's up to the user to ensure the underlying cursor object has not been opened by calling ```current``` or ```next```.

Add a common cursor interface

---

lib/Doctrine/MongoDB/EagerCursor.php
lib/Doctrine/MongoDB/Query/Query.php
tests/Doctrine/MongoDB/Tests/EagerCursorTest.php

Support $useKeys option when EagerCursor converts to an array

---

.travis.yml
lib/Doctrine/MongoDB/Cursor.php
lib/Doctrine/MongoDB/CursorInterface.php
lib/Doctrine/MongoDB/EagerCursor.php
lib/Doctrine/MongoDB/Query/Query.php
tests/Doctrine/MongoDB/Tests/CursorTest.php
tests/Doctrine/MongoDB/Tests/EagerCursorTest.php
tests/Doctrine/MongoDB/Tests/Query/QueryTest.php

This extends the common cursor interface introduced in #209 to include all methods currently available in the cursor. This makes the ```Cursor``` and ```EagerCursor``` more interchangeable in ODM, allowing us to plug both classes into ```ODM\Cursor``` once that has been adapted.
The ```hasNext``` and ```getNext``` methods have to be simulated by advancing and rewinding the array pointer as well as checking if the cursor has started iterating.

Include all cursor methods in cursor interface

---

lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php

As mentioned in doctrine/mongodb-odm#1224, there is no support for the $coment operator that was introduced in 2.4. This PR fixes that.

Add support for the $comment operator

---

lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php
tests/Doctrine/MongoDB/Tests/Query/FunctionalTest.php

This PR adds support for the [$etOnInsert operator](https://docs.mongodb.org/manual/reference/operator/update/setOnInsert/) that was added in MongoDB 2.4.

Add support for $setOnInsert operator

---

CHANGELOG-1.2.md
lib/Doctrine/MongoDB/Collection.php

This was initially introduced as #236 but needs to target 1.2.x support branch.

Fix bug where timeout is set to 1 ms

---

.travis.yml
composer.json
lib/Doctrine/MongoDB/Collection.php
lib/Doctrine/MongoDB/Connection.php
lib/Doctrine/MongoDB/Cursor.php
lib/Doctrine/MongoDB/Database.php
lib/Doctrine/MongoDB/Util/ReadPreference.php
tests/Doctrine/MongoDB/Tests/CollectionTest.php
tests/Doctrine/MongoDB/Tests/CommandCursorFunctionalTest.php
tests/Doctrine/MongoDB/Tests/ConnectionTest.php
tests/Doctrine/MongoDB/Tests/CursorTest.php
tests/Doctrine/MongoDB/Tests/DatabaseTest.php
tests/Doctrine/MongoDB/Tests/Util/ReadPreferenceTest.php

PHP 5.3 is no longer supported while PHP 5.4 is getting security updates only, so the next minor version upgrade (1.3.0) will require PHP 5.5 or 5.6. Please note that currently PHP 7 is not supported.
While we're at it, the new version will also bump the minimum driver versions. Thus, the 1.2, 1.3 and 1.4 versions of the mongo driver will no longer be supported and 1.5.0 or newer will be required.

Bump PHP and mongo version requirements

---

lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php
tests/Doctrine/MongoDB/Tests/Query/ExprTest.php

This PR adds the $caseSensitive and $diacriticInsensitive options to $text queries as well as the following operators:
* $bitsAllClear
* $bitsAllSet
* $bitsAnyClear
* $bitsAnySet

Add query operators introduced with MongoDB 3.2

---

lib/Doctrine/MongoDB/Query/Expr.php

`self` means the base class will always be returned. This is not only false, but breaks code completion in some editors when attempting to access derived class methods. For more information see [phpDocumentor types documentation](https://www.phpdoc.org/docs/latest/guides/types.html#keywords).

Corrected fluent interface docblocks

---

lib/Doctrine/MongoDB/Aggregation/Expr.php
tests/Doctrine/MongoDB/Tests/Aggregation/ExprTest.php

This adds the `expr()` method to the expression object the same way it is already available in the builder. This is helpful when needing to create a fresh expression object (to be nested inside) without having access to the actual aggregation builder.
This may be confusing due to the similarity to the `expression()` method that already exists (which can be used to apply an expression previously created with `expr()`) but I can't come up with any more meaningful name.

Add expr method to aggregation expression object

---

lib/Doctrine/MongoDB/Aggregation/Stage/Group.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/GroupTest.php

Fixes #254.
This change allows users to use operators in group stages for the ID field:
```
$builder
->group()
->field('_id')
->year('$dateField')
->field('count')
->sum(1);
```
Note: this will also allow building the following pipeline which is invalid and will error out on MongoDB when executed:
```
$builder
->group()
->field('_id')
->year('$dateField')
->field('month')
->month('$dateField');
```
I've decided against checking for this as this would require overwriting all operators declared in the `Operator` class to check whether the current field is an ID field and error out if it's not. People familiar with aggregation queries should be able to make this distinction on their own.

Allow using operators in group stages

---

lib/Doctrine/MongoDB/Aggregation/Builder.php

This will fix a PHP warning when calling `getPipeline()` on an Aggregation
builder without any stages since array_map expects an array as second argument, but the `$stages`
property is still `null`. The new behaviour is consistent with the Query builder, which also
returns an empty array.

Initialize the aggregation builder stages property with an empty array

---

.travis.yml
tests/Doctrine/MongoDB/Tests/ConnectionFunctionalTest.php

While composer.json has allowed installing on PHP 7 for a while (given that the `ext-mongo` requirement is fulfilled), there were no tests for that platform. This PR adds alcaeus/mongo-php-adapter as polyfill to the PHP 7 version of the build matrix.
Note: due to a [bug with composer](https://github.com/composer/composer/issues/5030) the build step installing the polyfill is running with the `ignore-platform-reqs` flag. Once this bug is fixed the flag should be removed.
Note 2: there is one test that would be failing and is skipped: mainly, it checks whether connecting/disconnecting updates the `connected` flag. Due to the new MongoDB driver not providing explicit connect/disconnect functionality the flag cannot be updated. Since this behavior should not cause too many problems in …

Add PHP 7 to the build matrix using polyfill

---

.travis.yml
composer.json

Since PHP 5.5 won't be supported after 10 July 2016, the upcoming 1.4 release will require PHP 5.6 (and PHP 7.0 using a polyfill).

Drop support for PHP 5.5

---

lib/Doctrine/MongoDB/Aggregation/Stage/Group.php
lib/Doctrine/MongoDB/Query/Builder.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/GeoNearTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/GroupTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/IndexStatsTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/LimitTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/LookupTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/MatchTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/OperatorTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/OutTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/ProjectTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/RedactTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/SampleTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/SkipTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/SortTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/UnwindTest.php
tests/Doctrine/MongoDB/Tests/CollectionTest.php
tests/Doctrine/MongoDB/Tests/CursorTest.php
tests/Doctrine/MongoDB/Tests/DatabaseTest.php
tests/Doctrine/MongoDB/Tests/EventTest.php
tests/Doctrine/MongoDB/Tests/LoggableCursorTest.php
tests/Doctrine/MongoDB/Tests/Query/QueryTest.php
tests/Doctrine/MongoDB/Tests/RetryTest.php

`grep` result revealed those unused uses while searching on this lib.
So I've corrected it using http://cs.sensiolabs.org/ tool.
Even though it isn't really important, less is better I think. :)

Removed unused use statements

---

lib/Doctrine/MongoDB/Query/Builder.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php

As discussed in doctrine/mongodb-odm#1501, we deprecate `update` and `multiple` for clarity, replacing them with `updateOne` and `updateMany` methods as it's done in `mongo/mongo`. This is mainly done for ODM version 2, where we will adapt the query builder to the new driver.

Deprecate update() and multiple() methods in query builder

---

lib/Doctrine/MongoDB/Aggregation/Builder.php
lib/Doctrine/MongoDB/Aggregation/Expr.php
lib/Doctrine/MongoDB/Aggregation/Stage.php
lib/Doctrine/MongoDB/Aggregation/Stage/Group.php
lib/Doctrine/MongoDB/Aggregation/Stage/Match.php
lib/Doctrine/MongoDB/Aggregation/Stage/Operator.php
lib/Doctrine/MongoDB/Aggregation/Stage/Out.php
lib/Doctrine/MongoDB/Aggregation/Stage/Project.php

This PR collects all changes necessary to support hydrated aggregation results in doctrine/mongodb-odm#1263.

Open up aggregation builder API for use in ODM

---

lib/Doctrine/MongoDB/Query/Query.php
tests/Doctrine/MongoDB/Tests/Query/QueryTest.php

Fixes #267.
This allows the user to pass in hint, limit, maxTimeMS and skip options when running count queries.

Pass query options when running count command

---

lib/Doctrine/MongoDB/Aggregation/Stage/Match.php
lib/Doctrine/MongoDB/Aggregation/Stage/Operator.php
lib/Doctrine/MongoDB/Connection.php
lib/Doctrine/MongoDB/LoggableDatabase.php
lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Traits/LoggableCollectionTrait.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/GroupTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/MatchTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/OperatorTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/ProjectTest.php
tests/Doctrine/MongoDB/Tests/CollectionEventsChangingContextTest.php
tests/Doctrine/MongoDB/Tests/Query/BuilderTest.php

Might as well use some of those beautiful features from PHP 5.6

Use argument unpacking instead of call_user_func

---

lib/Doctrine/MongoDB/Aggregation/Expr.php
lib/Doctrine/MongoDB/Aggregation/Stage/Match.php
lib/Doctrine/MongoDB/Aggregation/Stage/Operator.php
lib/Doctrine/MongoDB/Query/Builder.php
lib/Doctrine/MongoDB/Query/Expr.php

Fixes #262.
This allows passing multiple expressions to the `addAnd`, `addNor` and `addOr` methods in the query builder as well as the `addAnd` and `addOr` methods in the aggregation builder.

Allow passing multiple arguments to add* methods

---

lib/Doctrine/MongoDB/Aggregation/Stage/Sample.php
tests/Doctrine/MongoDB/Tests/Aggregation/BuilderTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/SampleTest.php

Added  'size'  attribute to the sample stage for query builder
With reference to the offical mongodb documentation
{ $sample: { size: <positive integer> } }

Fixed  sample stage

---

.travis.yml

This one tiny sleep hopefully fixes the build issues that we've been having. In addition to that, it's time to test against PHP 7.1. Unfortunately, adding `nightly` to the build fails due to segfaults when requiring mongo-php-adapter. Oh well.

Add PHP 7 to matrix and fix build issues

---

lib/Doctrine/MongoDB/Aggregation/Builder.php
lib/Doctrine/MongoDB/Aggregation/Stage/AddFields.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/AddFieldsTest.php

This PR adds the [`$addFields`](https://docs.mongodb.com/manual/reference/operator/aggregation/addFields/) operator which is new in MongoDB 3.4

Add $addFields operator to AggregationBuilder

---

lib/Doctrine/MongoDB/Aggregation/Builder.php
lib/Doctrine/MongoDB/Aggregation/Expr.php
lib/Doctrine/MongoDB/Aggregation/Stage.php
lib/Doctrine/MongoDB/Aggregation/Stage/AbstractBucket.php
lib/Doctrine/MongoDB/Aggregation/Stage/AddFields.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket/AbstractOutput.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket/BucketAutoOutput.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket/BucketOutput.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket/Output.php
lib/Doctrine/MongoDB/Aggregation/Stage/BucketAuto.php
lib/Doctrine/MongoDB/Aggregation/Stage/Count.php
lib/Doctrine/MongoDB/Aggregation/Stage/Facet.php
lib/Doctrine/MongoDB/Aggregation/Stage/GraphLookup.php
lib/Doctrine/MongoDB/Aggregation/Stage/GraphLookup/Match.php
lib/Doctrine/MongoDB/Aggregation/Stage/Lookup.php
lib/Doctrine/MongoDB/Aggregation/Stage/Project.php
lib/Doctrine/MongoDB/Aggregation/Stage/ReplaceRoot.php
lib/Doctrine/MongoDB/Aggregation/Stage/SortByCount.php
lib/Doctrine/MongoDB/Aggregation/Stage/Unwind.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/BucketAutoTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/BucketTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/CountTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/FacetTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/GraphLookupTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/ProjectTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/ReplaceRootTest.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/SortByCountTest.php

This pull requests adds support for the new aggregation pipeline stages added in MongoDB 3.4:
- `$bucket`
- `$bucketAuto`
- `$sortByCount`
- `$replaceRoot`
- `$facet`
- `$graphLookup`
- `$count`
Note: build will fail on PHP 5.6 until I've rebased this on top of #291, but I figured it's worth getting feedback in first.

Add support for aggregation pipeline stages added in MongoDB 3.4

---

.travis.yml
composer.json

So, turns out that `mongodb-enterprise` [could no longer be installed](https://travis-ci.org/doctrine/mongodb/jobs/261040827#L509), which is why we're now testing against `mongodb-org-server`. Unfortunately, the oldest available version is 3.0, so we're now testing against that as lowest version. To make matters more interesting, the 1.5 driver [causes interesting test failures](https://travis-ci.org/doctrine/mongodb/jobs/261488830#L562), so we're requiring `ext-mongo` 1.6 now. The lowest version to not [throw a segmentation fault](https://travis-ci.org/doctrine/mongodb/jobs/261536274#L552) is 1.6.7, so that will be our new `ext-mongo` requirement.

Test against PHP 7.2

---

CHANGELOG-1.6.md
UPGRADE-1.6.md
composer.json
lib/Doctrine/MongoDB/Aggregation/Expr.php
lib/Doctrine/MongoDB/Aggregation/Stage/AbstractBucket.php
lib/Doctrine/MongoDB/Aggregation/Stage/GraphLookup.php
lib/Doctrine/MongoDB/Aggregation/Stage/ReplaceRoot.php

This was introduced in #292 by adding a `convertExpression` method and using that in the expression operator methods. Unfortunately, MongoDB ODM relied on the `ensureArray` method being called to do the type conversion, which is no longer the case since all methods call `convertExpression`.

Fix BC break when converting expression objects

---

lib/Doctrine/MongoDB/Aggregation/Stage/AbstractBucket.php
lib/Doctrine/MongoDB/Aggregation/Stage/Bucket.php
lib/Doctrine/MongoDB/Aggregation/Stage/BucketAuto.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/BucketAutoTest.php

This fixes a rather silly copy/paste mistake on my part. I'll note that this fix technically constitutes a BC break, as we're adding a new abstract method to a class. Given the lack of bug reports and the fact that ODM 1.2 with support for the aggregation framework still hasn't hit yet, i'm willing to push the fix this way. Other option would be to have `getStageName` non-abstract and return `$bucket` in `AbstractBucket` and only override the method in `BucketAuto`.

Fix wrong name for $bucketAuto pipeline stage

---

tests/Doctrine/MongoDB/Tests/CursorTest.php
tests/Doctrine/MongoDB/Tests/EagerCursorTest.php
tests/Doctrine/MongoDB/Tests/GridFSTest.php
tests/Doctrine/MongoDB/Tests/RetryTest.php

Continuing to refactory tests, like #309, I used:
- `assertInternalType` instead of `is_*` functions;
- `assertCount` instead of `count` function;
- `assertArrayNotHasKey` instead of `array_key_exists` function.

Refactoring tests

---

lib/Doctrine/MongoDB/GridFS.php
lib/Doctrine/MongoDB/Query/Query.php

This bug can appear when working on a replica set and assigning GridFS documents a secondary read preference (e.g. via the `@ReadPreference` mapping in Doctrine MongoDB ODM). The library stores the file, then reads it from the database to fetch current metadata. If the document is using a secondary read preference, this can lead to the document not being found. Furthermore, due to insufficient error handling, this will not be a regular exception but a type error when assigning the result to the `GridFSFile` instance.
Last but not least, the file was read twice from the database with the result of the first read not being used, so this should also (slightly) improve performance of GridFS write operations.

Use primary read preference when reading newly peristed GridFS files

---

CHANGELOG-1.6.md
lib/Doctrine/MongoDB/Aggregation/Stage/ReplaceRoot.php
tests/Doctrine/MongoDB/Tests/Aggregation/Stage/ReplaceRootTest.php

This PR fixes a wrong syntax for replaceRoot, as reported in https://github.com/doctrine/DoctrineMongoDBBundle/issues/565.

Fix wrong syntax for replaceRoot stage

---

.doctrine-project.json

With ODM 2.0 released, we're no longer actively developing the MongoDB abstraction layer. We're also no longer actively supporting 1.x, except for critical fixes that impact ODM. Thus, the documentation should convey that people shouldn't use this project anymore.
This project will be archived once the maintenance period for ODM 1.x runs out (which will be around April 2020).

Update version information for documentation
